Repository banerjixplores/travel_trends, pull requests merged in 2025-05, with the labels that each got.

#53 modified project structure, workflow and iterations in core questions
  README.md
Labels: Day 1

#54 refactor: Improved ETL mapping functions and cleaned data labels
  data/processed/Travel details dataset_cleaned.csv
  jupyter_notebooks/Hackathon_Travel_Dataset.ipynb
Labels: Day 2

#55 Fix: Corrected destination country mapping to avoid data loss in ETL …
  jupyter_notebooks/Hackathon_Travel_Dataset.ipynb
Labels: bug

#56 Initial Basic Visualization
  Travel_Details.pbix
Labels: Day 2

#57 Feature Engineering + Visual Enhancements + Markdown Updates
  jupyter_notebooks/Hackathon_Travel_Dataset.ipynb
Labels: Day 2

#58 Iterated README with ETL and visual developments
  README.md
Labels: Day 2

#59 incorporated styling for better readability
  README.md
Labels: documentation

#60 Styling changes: Project structure
  README.md
Labels: documentation

#66 Final changes
  README.md
  dashboard/Travel_Details.pbix
Labels: Day 3
